name: iOS Testing Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SCHEME: CryptoLiveActivity

jobs:
  build:
    name: Build and Test using ${{ matrix.xcode_version }} iOS ${{ matrix.os_version }}
    runs-on: macos-14
    timeout-minutes: 10
    strategy:
      fail-fast: true
      matrix:
        # https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md#installed-simulators
        xcode_version: [ "15.0.1", "15.1", "15.2" ]
        os_version: [ "17.0.1", "17.1", "17.2" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Xcode
        uses: actions/setup-xcode@v2
        with:
          xcode-version: ${{ matrix.xcode_version }}
      - name: Build
        run: |
          # https://mokacoding.com/blog/xcodebuild-destination-options/
          xcodebuild \
            -scheme "$SCHEME" \
            -destination "platform=iOS Simulator,name=iPhone 14,OS=${{ matrix.os_version }}" \
            build-for-testing
