name: iOS Testing Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SCHEME: CryptoLiveActivity

jobs:
  build:
    # https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md#installed-simulators
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          # https://mokacoding.com/blog/xcodebuild-destination-options/
          xcodebuild \
            -scheme "$SCHEME" \
            -destination "platform=iOS Simulator,name=iPhone 14,OS=17.0.1" \
            build-for-testing
